## La importancia de la limpieza y procesamiento de datos previos: Sentando las bases para un análisis confiable

#### Ayudantia 08 - IMT2000

La limpieza y procesamiento de datos previos son etapas fundamentales en cualquier proyecto de análisis de datos. Estas etapas implican identificar y corregir errores, eliminar valores atípicos y duplicados, y manejar los valores faltantes. Al realizar estas tareas, se garantiza la calidad y confiabilidad de los datos, lo que a su vez mejora la precisión y confiabilidad de los análisis y modelos resultantes. Además, el preprocesamiento de datos permite optimizar el rendimiento de los algoritmos y facilita la interpretación y toma de decisiones basadas en información confiable. En definitiva, la limpieza y procesamiento de datos previos sientan las bases para un análisis confiable y significativo.

In [1]:
# Importar bibliotecas necesarias
import pandas as pd

# Crear un DataFrame de ejemplo
data = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luisa'],
    'Edad': [25, 30, 35, 28, 42],
    'Altura': [1.75, 1.68, 1.80, 1.62, 1.70],
    'Casado': [False, True, False, True, True]
})

In [2]:
data

   ID Nombre  Edad  Altura  Casado
0   1   Juan    25    1.75   False
1   2  María    30    1.68    True
2   3  Pedro    35    1.80   False
3   4    Ana    28    1.62    True
4   5  Luisa    42    1.70    True

## 1. Manejo de valores nulos

Es importante identificar y manejar los valores nulos en los conjuntos de datos. Podemos utilizar el método ``isnull()`` para verificar si hay valores nulos en nuestro conjunto de datos y luego usar métodos como ``dropna()`` o ``fillna()`` para manejarlos.

In [8]:
# Verificar valores nulos
data.isnull().sum()

ID        0
Nombre    0
Edad      0
Altura    0
Casado    0
dtype: int64

## 2. Eliminación de valores duplicados

Otro paso importante en la limpieza de datos es eliminar los valores duplicados. Podemos utilizar el método ``duplicated()`` para identificar los duplicados y luego usar ``drop_duplicates()`` para eliminarlos.

In [5]:
# Verificar valores duplicados
data.duplicated().sum()

0

Otro método útil es el de ``nunique()`` que te entrega el número de elementos únicos de una columna.

In [9]:
# Verificamos los valores unicos
data.nunique()

ID        5
Nombre    5
Edad      5
Altura    5
Casado    2
dtype: int64

## 3. Corrección de tipos de datos

A veces, los tipos de datos pueden estar incorrectos en nuestro conjunto de datos. Podemos utilizar métodos como ``astype()`` para convertir los tipos de datos a los apropiados.

In [10]:
# Convertir tipo de datos de la columna 'Monto_Venta' a float
data['Monto_Venta'] = data['Monto_Venta'].astype(float)

# Verificar los cambios
data.dtypes

KeyError: 'Monto_Venta'

cada tipo de dato:

- int64: Representa valores enteros. En el ejemplo, la columna "ID" y "Edad" son de tipo entero.

- float64: Representa valores decimales. En el ejemplo, la columna "Altura" es de tipo float.

- object: Representa valores de tipo cadena de texto (strings). En el ejemplo, la columna "Nombre" es de tipo objeto (object).

- bool: Representa valores booleanos (True o False). En el ejemplo, la columna "Casado" es de tipo booleano.

Es importante tener en cuenta los tipos de datos de las columnas en un DataFrame, ya que pueden afectar el análisis y las operaciones que se pueden realizar. En algunos casos, es posible que sea necesario convertir los tipos de datos a otros más apropiados para ciertas operaciones, como convertir cadenas de texto a fechas o números.

Actividad

En esta ocación usaremos el dataset de ``imdb_1000.xlx`` el cual contiene el top 1000 de peliculas de la plataforma IMDB: ``https://www.imdb.com``

Recuerda colocarlo en el mismo directorio o carpeta que el archivo jupyter de la ayudantía.

Datos:

- Poster_Link: Enlace al póster utilizado por IMDb.
- Series_Title: Nombre de la película.
- Released_Year: Año en que se estrenó la película.
- Certificate: Certificado obtenido por la película.
- Runtime: Duración total de la película.
- Genre: Género de la película.
- IMDB_Rating: Calificación de la película en el sitio web de IMDb.
- Overview: Resumen o sinopsis de la película.
- Meta_score: Puntuación obtenida por la película.
- Director: Nombre del director.
- Star1, Star2, Star3, Star4: Nombres de las estrellas (actores/actrices) de la película.
- No_of_votes: Número total de votos recibidos.
- Gross: Ganancias monetarias obtenidas por la película.

* En caso de no haber asistido a ayudantías anteriores, es necesario hacer pip install openpyxl

1.Limpieza:

La tarea es que realicen una limpieza correcta de el dataset y procecen los datos de manera que puedan ser bien utlizados para analisis.

El dataset final debe:

- Tener una nueva columna llamada "Top" que diga el número del top de la pelicula.

- No contener filas con valores nulos, excepto las filas que contengan valores nulos en las columnas de "Star" en estas reemplazar el valor nulo por "Nadie" ,elimine el resto de filas del dataframe.

- Tener correcto el tipo de dato que representa la columna, si es numerico, string u otro.

- El nombre de las columnas debe ser descriptivo, en español, y sin espacios. Se recomienda usar el "_" para representar espacios.

- Eliminar las columnas de "Certificate" y "Meta_score", ya que, no son relevantes para el analisis.

In [12]:
# -----------------------------
data = pd.read_excel("imdb_1000.xlsx")
data.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"$28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"$134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"$534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"$57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"$4,360,000"

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          985 non-null    object
 13  Star4          990 non-null    object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

## Columna TOP

In [15]:
df = data.copy()

In [19]:
df.sort_values(by="IMDB_Rating", ascending=False, inplace=True)

In [20]:
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"$28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"$134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"$534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"$57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"$4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,https://m.media-amazon.com/images/M/MV5BMTU5MD...,Zombieland,2009,A,88 min,"Adventure, Comedy, Fantasy",7.6,A shy student trying to reach his family in Oh...,73.0,Ruben Fleischer,Jesse Eisenberg,Emma Stone,Woody Harrelson,Abigail Breslin,520041,"$75,590,286"
911,https://m.media-amazon.com/images/M/MV5BYmFmNj...,La piel que habito,2011,R,120 min,"Drama, Horror, Thriller",7.6,"A brilliant plastic surgeon, haunted by past t...",70.0,Pedro Almodóvar,Antonio Banderas,Elena Anaya,Jan Cornet,Marisa Paredes,138959,"$3,185,812"
910,https://m.media-amazon.com/images/M/MV5BMjAxOT...,Moneyball,2011,PG-13,133 min,"Biography, Drama, Sport",7.6,Oakland A's general manager Billy Beane's succ...,87.0,Bennett Miller,Brad Pitt,Robin Wright,Jonah Hill,Philip Seymour Hoffman,369529,"$75,605,492"
909,https://m.media-amazon.com/images/M/MV5BMjI2OD...,Celda 211,2009,NaN,113 min,"Action, Adventure, Crime",7.6,The story of two men on different sides of a p...,NaN,Daniel Monzón,Luis Tosar,Alberto Ammann,Antonio Resines,Manuel Morón,63882,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [21]:
top = list(range(1, 1001))
df["Top"] = top
df["Top"]

0         1
1         2
2         3
3         4
4         5
       ...
912     996
911     997
910     998
909     999
999    1000
Name: Top, Length: 1000, dtype: int64

In [22]:
df.head(5)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"$28,341,469",1
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"$134,966,411",2
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"$534,858,444",3
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"$57,300,000",4
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"$4,360,000",5

## Eliminar filas nulas fuera de "Star"

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          985 non-null    object
 13  Star4          990 non-null    object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
 16  Top            1000 non-null   int64
dtypes: float64(2), int64(2), object(13)
memory usage: 140.6+ KB

In [24]:
df["Star3"].fillna("Nadie", inplace=True)
df["Star4"].fillna("Nadie", inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
 16  Top            1000 non-null   int64
dtypes: float64(2), int64(2), object(13)
memory usage: 140.6+ KB

In [29]:
df.dropna(inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 910
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    714 non-null    object
 1   Series_Title   714 non-null    object
 2   Released_Year  714 non-null    object
 3   Certificate    714 non-null    object
 4   Runtime        714 non-null    object
 5   Genre          714 non-null    object
 6   IMDB_Rating    714 non-null    float64
 7   Overview       714 non-null    object
 8   Meta_score     714 non-null    float64
 9   Director       714 non-null    object
 10  Star1          714 non-null    object
 11  Star2          714 non-null    object
 12  Star3          714 non-null    object
 13  Star4          714 non-null    object
 14  No_of_Votes    714 non-null    int64
 15  Gross          714 non-null    object
 16  Top            714 non-null    int64
dtypes: float64(2), int64(2), object(13)
memory usage: 100.4+ KB

Buscamos información para completar el dataframe

In [32]:
df[df["Released_Year"] == "PG"]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"$173,837,933",890

In [40]:
df.reset_index(inplace=True)

ValueError: cannot insert level_0, already exists

In [ ]:
df = df.drop(columns=["level_0", "index"], axis=1)

In [46]:
df[df["Released_Year"] == "PG"]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
618,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"$173,837,933",890

In [55]:
df.at[618, "Released_Year"] = 1995
df.iloc[618, :]

Poster_Link      https://m.media-amazon.com/images/M/MV5BNjEzYj...
Series_Title                                             Apollo 13
Released_Year                                                 1995
Certificate                                                      U
Runtime                                                    140 min
Genre                                    Adventure, Drama, History
IMDB_Rating                                                    7.6
Overview         NASA must devise a strategy to return Apollo 1...
Meta_score                                                    77.0
Director                                                Ron Howard
Star1                                                    Tom Hanks
Star2                                                  Bill Paxton
Star3                                                  Kevin Bacon
Star4                                                  Gary Sinise
No_of_Votes                                                 269197
Gross                                                 $173,837,933
Top                                                            890
Name: 618, dtype: object

In [56]:
df["Series_Title"] = df["Series_Title"].astype(str)
df["Released_Year"] = df["Released_Year"].astype(int)
df["Gross"] = df["Gross"].astype(str)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    714 non-null    object
 1   Series_Title   714 non-null    object
 2   Released_Year  714 non-null    int32
 3   Certificate    714 non-null    object
 4   Runtime        714 non-null    object
 5   Genre          714 non-null    object
 6   IMDB_Rating    714 non-null    float64
 7   Overview       714 non-null    object
 8   Meta_score     714 non-null    float64
 9   Director       714 non-null    object
 10  Star1          714 non-null    object
 11  Star2          714 non-null    object
 12  Star3          714 non-null    object
 13  Star4          714 non-null    object
 14  No_of_Votes    714 non-null    int64
 15  Gross          714 non-null    object
 16  Top            714 non-null    int64
dtypes: float64(2), int32(1), int64(2), object(12)
memory usage: 92.2+ KB

In [59]:
columnas = ["nombre_pelicula", "lanzamiento", "Certificado", "Duracion", "Genero"]
df = df.rename(columns = {"Series_Title": "nombre_pelicula", 
                          "Released_Year": "lanzamiento", 
                          "Certificate": "Certificado", "Runtime": "Duracion",
                         "Genre": "Genero"})

df.columns

Index(['Poster_Link', 'nombre_pelicula', 'lanzamiento', 'Certificado',
       'Duracion', 'Genero', 'IMDB_Rating', 'Overview', 'Meta_score',
       'Director', 'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross',
       'Top'],
      dtype='object')

In [61]:
df.drop(columns=["Certificado", "Meta_score"], axis=1, inplace=True)

In [62]:
df

,Poster_Link,nombre_pelicula,lanzamiento,Duracion,Genero,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"$28,341,469",1
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"$134,966,411",2
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"$534,858,444",3
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"$57,300,000",4
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"$4,360,000",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,https://m.media-amazon.com/images/M/MV5BMjEzOT...,The Blind Side,2009,129 min,"Biography, Drama, Sport",7.6,"The story of Michael Oher, a homeless and trau...",John Lee Hancock,Quinton Aaron,Sandra Bullock,Tim McGraw,Jae Head,293266,"$255,959,475",993
710,https://m.media-amazon.com/images/M/MV5BMTg0Nj...,Sherlock Holmes,2009,128 min,"Action, Adventure, Mystery",7.6,Detective Sherlock Holmes and his stalwart par...,Guy Ritchie,Robert Downey Jr.,Jude Law,Rachel McAdams,Mark Strong,583158,"$209,028,679",994
711,https://m.media-amazon.com/images/M/MV5BMTU5MD...,Zombieland,2009,88 min,"Adventure, Comedy, Fantasy",7.6,A shy student trying to reach his family in Oh...,Ruben Fleischer,Jesse Eisenberg,Emma Stone,Woody Harrelson,Abigail Breslin,520041,"$75,590,286",996
712,https://m.media-amazon.com/images/M/MV5BYmFmNj...,La piel que habito,2011,120 min,"Drama, Horror, Thriller",7.6,"A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,Antonio Banderas,Elena Anaya,Jan Cornet,Marisa Paredes,138959,"$3,185,812",997
713,https://m.media-amazon.com/images/M/MV5BMjAxOT...,Moneyball,2011,133 min,"Biography, Drama, Sport",7.6,Oakland A's general manager Billy Beane's succ...,Bennett Miller,Brad Pitt,Robin Wright,Jonah Hill,Philip Seymour Hoffman,369529,"$75,605,492",998

2.Analisis:

- Muestren es la pelicula más vieja del top y en qué top está.

- Muestren el director que tiene más peliculas en el top.

- Muestren el promedio de los tiempos de duración de todas las peliculas que tenga cada director.

- Tomen su director favorito y muestren un analisis de su crítica y taquilla, es decir, obtener en un unico dataframe la mejor y peor pelicula según el ranking IMDB y otro dataframe que muestre la pelicula que haya tenido mayor y menor ganancias.

In [63]:
df1 = df.copy()

In [66]:
df1.sort_values(by="lanzamiento", inplace=True)
# Como ordenamos el dataframe, la primera fila, será la película más vieja.

df1.iloc[0, -1]

373

In [67]:
df1.iloc[0, :]

Poster_Link        https://m.media-amazon.com/images/M/MV5BMzg2MW...
nombre_pelicula                       All Quiet on the Western Front
lanzamiento                                                     1930
Duracion                                                     152 min
Genero                                                    Drama, War
IMDB_Rating                                                      8.0
Overview           A German youth eagerly enters World War I, but...
Director                                             Lewis Milestone
Star1                                                      Lew Ayres
Star2                                                  Louis Wolheim
Star3                                                      John Wray
Star4                                                    Arnold Lucy
No_of_Votes                                                    57318
Gross                                                     $3,270,000
Top                                                              373
Name: 240, dtype: object

## Director con más peliculas

In [71]:
df1.groupby(by="Director").count()["Top"].sort_values()

Director
Abdellatif Kechiche     1
Merian C. Cooper        1
Mel Stuart              1
Matt Ross               1
Matt Reeves             1
                       ..
David Fincher           8
Quentin Tarantino       8
Alfred Hitchcock        9
Martin Scorsese        10
Steven Spielberg       13
Name: Top, Length: 402, dtype: int64

# Promedios duración

In [82]:
df1["Duracion"] = df1["Duracion"].apply(lambda x: x.rstrip(" min")).astype(int)

In [83]:
df1.head(2)

,Poster_Link,nombre_pelicula,lanzamiento,Duracion,Genero,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
240,https://m.media-amazon.com/images/M/MV5BMzg2MW...,All Quiet on the Western Front,1930,152,"Drama, War",8.0,"A German youth eagerly enters World War I, but...",Lewis Milestone,Lew Ayres,Louis Wolheim,John Wray,Arnold Lucy,57318,"$3,270,000",373
32,https://m.media-amazon.com/images/M/MV5BY2I4Mm...,City Lights,1931,87,"Comedy, Drama, Romance",8.5,"With the aid of a wealthy erratic tippler, a d...",Charles Chaplin,Charles Chaplin,Virginia Cherrill,Florence Lee,Harry Myers,167839,"$19,181",38

In [84]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 240 to 685
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Poster_Link      714 non-null    object
 1   nombre_pelicula  714 non-null    object
 2   lanzamiento      714 non-null    int32
 3   Duracion         714 non-null    int32
 4   Genero           714 non-null    object
 5   IMDB_Rating      714 non-null    float64
 6   Overview         714 non-null    object
 7   Director         714 non-null    object
 8   Star1            714 non-null    object
 9   Star2            714 non-null    object
 10  Star3            714 non-null    object
 11  Star4            714 non-null    object
 12  No_of_Votes      714 non-null    int64
 13  Gross            714 non-null    object
 14  Top              714 non-null    int64
dtypes: float64(1), int32(2), int64(2), object(10)
memory usage: 83.7+ KB

In [85]:
df1.groupby(by="Director").mean()["Duracion"]

Director
Abdellatif Kechiche    180.0
Abhishek Kapoor        130.0
Adam McKay             130.0
Akira Kurosawa         184.5
Alan J. Pakula         138.0
                       ...
Yimou Zhang            120.0
Yoshiaki Kawajiri      103.0
Yôjirô Takita          130.0
Zack Snyder            139.5
Zoya Akhtar            154.0
Name: Duracion, Length: 402, dtype: float64

# Crítica

In [86]:
# Elegir un director, ver su mejor y peor película según ranking IMDB, ver la con más y menos ganancias

df2 = df1[df1["Director"] == "Steven Spielberg"]
df2

,Poster_Link,nombre_pelicula,lanzamiento,Duracion,Genero,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
207,https://m.media-amazon.com/images/M/MV5BMmVmOD...,Jaws,1975,124,"Adventure, Thriller",8.0,When a killer shark unleashes chaos on a beach...,Steven Spielberg,Roy Scheider,Robert Shaw,Richard Dreyfuss,Lorraine Gary,543388,"$260,000,000",325
645,https://m.media-amazon.com/images/M/MV5BMjM1Nj...,Close Encounters of the Third Kind,1977,138,"Drama, Sci-Fi",7.6,"Roy Neary, an electric lineman, watches how hi...",Steven Spielberg,Richard Dreyfuss,François Truffaut,Teri Garr,Melinda Dillon,184966,"$132,088,635",922
49,https://m.media-amazon.com/images/M/MV5BMjA0OD...,Raiders of the Lost Ark,1981,115,"Action, Adventure",8.4,"In 1936, archaeologist and adventurer Indiana ...",Steven Spielberg,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,884112,"$248,159,971",57
419,https://m.media-amazon.com/images/M/MV5BMTQ2OD...,E.T. the Extra-Terrestrial,1982,115,"Family, Sci-Fi",7.8,A troubled child summons the courage to help a...,Steven Spielberg,Henry Thomas,Drew Barrymore,Peter Coyote,Dee Wallace,372490,"$435,110,554",631
409,https://m.media-amazon.com/images/M/MV5BZDRkOW...,The Color Purple,1985,154,Drama,7.8,A black Southern woman struggles to find her i...,Steven Spielberg,Danny Glover,Whoopi Goldberg,Oprah Winfrey,Margaret Avery,78321,"$98,467,863",606
495,https://m.media-amazon.com/images/M/MV5BMmQwNz...,Empire of the Sun,1987,153,"Action, Drama, History",7.7,A young English boy struggles to survive under...,Steven Spielberg,Christian Bale,John Malkovich,Miranda Richardson,Nigel Havers,115677,"$22,238,696",732
106,https://m.media-amazon.com/images/M/MV5BMjNkMz...,Indiana Jones and the Last Crusade,1989,127,"Action, Adventure",8.2,"In 1938, after his father Professor Henry Jone...",Steven Spielberg,Harrison Ford,Sean Connery,Alison Doody,Denholm Elliott,692366,"$197,171,806",139
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,195,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"$96,898,818",8
150,https://m.media-amazon.com/images/M/MV5BMjM2MD...,Jurassic Park,1993,127,"Action, Adventure, Sci-Fi",8.1,A pragmatic paleontologist visiting an almost ...,Steven Spielberg,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,867615,"$402,453,882",224
28,https://m.media-amazon.com/images/M/MV5BZjhkMD...,Saving Private Ryan,1998,169,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,1235804,"$216,540,909",33
194,https://m.media-amazon.com/images/M/MV5BMTY5Mz...,Catch Me If You Can,2002,141,"Biography, Crime, Drama",8.1,"Barely 21 yet, Frank is a skilled forger who h...",Steven Spielberg,Leonardo DiCaprio,Tom Hanks,Christopher Walken,Martin Sheen,832846,"$164,615,351",308
623,https://m.media-amazon.com/images/M/MV5BZTI3Yz...,Minority Report,2002,145,"Action, Crime, Mystery",7.6,In a future where a special police unit is abl...,Steven Spielberg,Tom Cruise,Colin Farrell,Samantha Morton,Max von Sydow,508417,"$132,072,926",895
676,https://m.media-amazon.com/images/M/MV5BMjIxOT...,Bridge of Spies,2015,142,"Drama, History, Thriller",7.6,"During the Cold War, an American lawyer is rec...",Steven Spielberg,Tom Hanks,Mark Rylance,Alan Alda,Amy Ryan,287659,"$72,313,754",955

In [87]:
df_ranking = df2.copy()
df_money = df2.copy()

In [88]:
# Ranking

df_ranking.sort_values(by="IMDB_Rating", inplace=True)

In [92]:
df_ranking.reset_index(inplace=True)

In [97]:
df_ranking = df_ranking.iloc[[0,-1],:]
df_ranking

,index,Poster_Link,nombre_pelicula,lanzamiento,Duracion,Genero,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
0,645,https://m.media-amazon.com/images/M/MV5BMjM1Nj...,Close Encounters of the Third Kind,1977,138,"Drama, Sci-Fi",7.6,"Roy Neary, an electric lineman, watches how hi...",Steven Spielberg,Richard Dreyfuss,François Truffaut,Teri Garr,Melinda Dillon,184966,"$132,088,635",922
12,7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,195,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"$96,898,818",8

# Ganancias

In [99]:
df_money["Gross"] = df_money["Gross"].apply(lambda x: x.lstrip("$").replace(",", "")).astype(int)
df_money.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 207 to 676
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Poster_Link      13 non-null     object
 1   nombre_pelicula  13 non-null     object
 2   lanzamiento      13 non-null     int32
 3   Duracion         13 non-null     int32
 4   Genero           13 non-null     object
 5   IMDB_Rating      13 non-null     float64
 6   Overview         13 non-null     object
 7   Director         13 non-null     object
 8   Star1            13 non-null     object
 9   Star2            13 non-null     object
 10  Star3            13 non-null     object
 11  Star4            13 non-null     object
 12  No_of_Votes      13 non-null     int64
 13  Gross            13 non-null     int32
 14  Top              13 non-null     int64
dtypes: float64(1), int32(3), int64(2), object(9)
memory usage: 1.5+ KB

In [100]:
df_money.sort_values(by="Gross", inplace=True)

In [101]:
df_money.reset_index(inplace=True)

In [102]:
df_money = df_money.iloc[[0,-1], :]
df_money

,index,Poster_Link,nombre_pelicula,lanzamiento,Duracion,Genero,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Top
0,495,https://m.media-amazon.com/images/M/MV5BMmQwNz...,Empire of the Sun,1987,153,"Action, Drama, History",7.7,A young English boy struggles to survive under...,Steven Spielberg,Christian Bale,John Malkovich,Miranda Richardson,Nigel Havers,115677,22238696,732
12,419,https://m.media-amazon.com/images/M/MV5BMTQ2OD...,E.T. the Extra-Terrestrial,1982,115,"Family, Sci-Fi",7.8,A troubled child summons the courage to help a...,Steven Spielberg,Henry Thomas,Drew Barrymore,Peter Coyote,Dee Wallace,372490,435110554,631